"""inventory and kardex models

Revision ID: 92ca549c9c8d
Revises: 91de8aa298ca
Create Date: 2026-01-27 23:40:41.027462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ca549c9c8d'
down_revision = '91de8aa298ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_type', sa.String(length=20), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'product_id', 'location_type', 'location_id', name='uq_inventory_company_product_location')
    )
    with op.batch_alter_table('inventories', schema=None) as batch_op:
        batch_op.create_index('ix_inventory_company_location', ['company_id', 'location_type', 'location_id'], unique=False)

    op.create_table('kardex_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('move_type', sa.String(length=20), nullable=False),
    sa.Column('from_location_type', sa.String(length=20), nullable=True),
    sa.Column('from_location_id', sa.Integer(), nullable=True),
    sa.Column('to_location_type', sa.String(length=20), nullable=True),
    sa.Column('to_location_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['from_location_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kardex_movements', schema=None) as batch_op:
        batch_op.create_index('ix_kardex_company_from', ['company_id', 'from_location_type', 'from_location_id'], unique=False)
        batch_op.create_index('ix_kardex_company_product_date', ['company_id', 'product_id', 'created_at'], unique=False)
        batch_op.create_index('ix_kardex_company_to', ['company_id', 'to_location_type', 'to_location_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kardex_movements', schema=None) as batch_op:
        batch_op.drop_index('ix_kardex_company_to')
        batch_op.drop_index('ix_kardex_company_product_date')
        batch_op.drop_index('ix_kardex_company_from')

    op.drop_table('kardex_movements')
    with op.batch_alter_table('inventories', schema=None) as batch_op:
        batch_op.drop_index('ix_inventory_company_location')

    op.drop_table('inventories')
    # ### end Alembic commands ###
