"""sale indexes and relationships

Revision ID: e1a32dc06825
Revises: 0b695488a141
Create Date: 2026-01-28 00:41:29.089583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a32dc06825'
down_revision = '0b695488a141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_items_sale_id'), ['sale_id'], unique=False)
        batch_op.create_index('ix_sale_items_sale_product', ['sale_id', 'product_id'], unique=False)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_client_id'), ['client_id'], unique=False)
        batch_op.create_index('ix_sales_company_branch_created', ['company_id', 'branch_id', 'created_at'], unique=False)
        batch_op.create_index('ix_sales_company_created', ['company_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_created_at'))
        batch_op.drop_index(batch_op.f('ix_sales_company_id'))
        batch_op.drop_index('ix_sales_company_created')
        batch_op.drop_index('ix_sales_company_branch_created')
        batch_op.drop_index(batch_op.f('ix_sales_client_id'))
        batch_op.drop_index(batch_op.f('ix_sales_branch_id'))

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.drop_index('ix_sale_items_sale_product')
        batch_op.drop_index(batch_op.f('ix_sale_items_sale_id'))
        batch_op.drop_index(batch_op.f('ix_sale_items_product_id'))

    # ### end Alembic commands ###
